DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS user_session;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS tag_post;
DROP TABLE IF EXISTS reply;
DROP TABLE IF EXISTS reply_like;

CREATE TABLE user (
	id	        INTEGER         PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	account	    VARCHAR(255)	NOT NULL,
	password	VARCHAR(255)	NOT NULL,
	name	    VARCHAR(255)	NOT NULL,
	nickname	VARCHAR(255)	NULL,
	profession	VARCHAR(255)	NULL,
	gender	    VARCHAR(255)	NULL,
	content	    VARCHAR(255)	NULL,
	birthday	VARCHAR(255)	NULL,
	image_url   VARCHAR(255)	NULL,
	is_auth	    VARCHAR(255)	NULL,
	created_at	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	updated_at	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	is_deleted	INTEGER 	NOT NULL	DEFAULT 0,
	UNIQUE(account)
);

CREATE TABLE user_session (
    id          INTEGER     PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_id     INTEGER     NOT NULL,
    name        VARCHAR(255),
    created_at	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
    updated_at	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tag (
    id          INTEGER     PRIMARY KEY AUTO_INCREMENT NOT NULL,
    post_id     INTEGER     NOT NULL,
    content     VARCHAR(255),
    created_at	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
    updated_at	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted	INTEGER 	NOT NULL	DEFAULT 0
);

CREATE TABLE tag_post (
    id          INTEGER     PRIMARY KEY AUTO_INCREMENT NOT NULL,
    tag_id      INTEGER     NOT NULL,
    post_id     INTEGER     NOT NULL,
    created_at	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
    updated_at	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted	INTEGER 	NOT NULL	DEFAULT 0
);

CREATE TABLE reply (
    id          INTEGER     PRIMARY KEY AUTO_INCREMENT NOT NULL,
    comment_id  INTEGER     NOT NULL,
    user_id     INTEGER     NOT NULL,
    content     VARCHAR(500)     NOT NULL,
    created_at	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
    updated_at	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted	INTEGER 	NOT NULL	DEFAULT 0
);

CREATE TABLE reply_like (
    id          INTEGER     PRIMARY KEY AUTO_INCREMENT NOT NULL,
    reply_id    INTEGER     NOT NULL,
    user_id     INTEGER     NOT NULL,
    is_deleted	INTEGER 	NOT NULL	DEFAULT 0
);

